app:
    resource: "@AppBundle/Controller/"
    type:     annotation

places:
    path: /places
    defaults: { _controller: AppBundle::PlacesController }

result:
    path: /result
    defaults: { _controller: AppBundle::PlacesController }