app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    defaults: { _controller: AppBundle:PlacesController:places }

result:
    path: /result
    defaults: { _controller: AppBundle:PlacesController:result }